### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by ginkel** [marudor/BahnhofsAbfahrten#28]
**Describe the bug**
When accessing https://marudor.de/K%C3%B6ln%20Messe%2FDeutz the page briefly displays the departures, but then turns white. The browser console shows the following error:

```
Navigated to https://marudor.de/K%C3%B6ln%20Messe%2FDeutz
main-24621523bb166aa1016f.js:1 Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://marudor.de/static/main-24621523bb166aa1016f.js:1:566495
    at i (https://marudor.de/static/main-24621523bb166aa1016f.js:1:566598)
    at Xi (https://marudor.de/static/main-24621523bb166aa1016f.js:1:661337)
    at Object.enqueueSetState (https://marudor.de/static/main-24621523bb166aa1016f.js:1:610828)
    at t.x.setState (https://marudor.de/static/main-24621523bb166aa1016f.js:1:558271)
    at t.n.internalSetState (https://marudor.de/static/main-24621523bb166aa1016f.js:1:274791)
    at t.n.componentDidUpdate (https://marudor.de/static/main-24621523bb166aa1016f.js:1:286631)
    at Bi (https://marudor.de/static/main-24621523bb166aa1016f.js:1:648567)
    at Wi (https://marudor.de/static/main-24621523bb166aa1016f.js:1:651143)
    at https://marudor.de/static/main-24621523bb166aa1016f.js:1:664350
fi @ main-24621523bb166aa1016f.js:1
n.callback @ main-24621523bb166aa1016f.js:1
ri @ main-24621523bb166aa1016f.js:1
ni @ main-24621523bb166aa1016f.js:1
Bi @ main-24621523bb166aa1016f.js:1
Wi @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
t.unstable_runWithPriority @ main-24621523bb166aa1016f.js:1
Ml @ main-24621523bb166aa1016f.js:1
Pl @ main-24621523bb166aa1016f.js:1
kl @ main-24621523bb166aa1016f.js:1
El @ main-24621523bb166aa1016f.js:1
Xi @ main-24621523bb166aa1016f.js:1
Il @ main-24621523bb166aa1016f.js:1
_l @ main-24621523bb166aa1016f.js:1
Ul.render @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
Nl @ main-24621523bb166aa1016f.js:1
Hl @ main-24621523bb166aa1016f.js:1
hydrate @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
n @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
n @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
n @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
(anonymous) @ main-24621523bb166aa1016f.js:1
main-24621523bb166aa1016f.js:1 Uncaught Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://marudor.de/static/main-24621523bb166aa1016f.js:1:566495
    at i (https://marudor.de/static/main-24621523bb166aa1016f.js:1:566598)
    at Xi (https://marudor.de/static/main-24621523bb166aa1016f.js:1:661337)
    at Object.enqueueSetState (https://marudor.de/static/main-24621523bb166aa1016f.js:1:610828)
    at t.x.setState (https://marudor.de/static/main-24621523bb166aa1016f.js:1:558271)
    at t.n.internalSetState (https://marudor.de/static/main-24621523bb166aa1016f.js:1:274791)
    at t.n.componentDidUpdate (https://marudor.de/static/main-24621523bb166aa1016f.js:1:286631)
    at Bi (https://marudor.de/static/main-24621523bb166aa1016f.js:1:648567)
    at Wi (https://marudor.de/static/main-24621523bb166aa1016f.js:1:651143)
    at https://marudor.de/static/main-24621523bb166aa1016f.js:1:664350
```

**Desktop (please complete the following information):**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by marudor** [comment]
Rolled back, closed.
